FROM wordpress

RUN apt update
RUN apt install git-all -y
RUN apt install nodejs -y
RUN apt install zip -y

# Yarn
RUN apt install gnupg -y
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - 
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt update
RUN apt install yarn -y